///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CModule1 = {0x3fd9384d,0xb70e,0x4470,{0xbb,0x6c,0xe7,0x1d,0xb5,0x3c,0xb3,0x53}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1DefaultAdsPort = 0x00000001;
const PTCID PID_Module1Counter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#pragma pack(push,1)
typedef struct _Module1Inputs
{
	LONG Position1;
	LONG Velocity1;
	USHORT Statusword1;
	LONG Position2;
	LONG Velocity2;
	USHORT Statusword2;
} Module1Inputs, *PModule1Inputs;
#pragma pack(pop)

typedef struct _Module1Outputs
{
	USHORT Controlword1;
	SHORT TargetTorque1;
	USHORT Controlword2;
	SHORT TargetTorque2;
} Module1Outputs, *PModule1Outputs;

#pragma pack(push,1)
typedef struct _Module1DeviceStates
{
	LONG U;
	LONG V;
	LONG W;
	LONG Angle1;
	LONG Angle2;
	LONG AngleZero1;
	LONG AngleZero2;
	bool MotorState1;
	bool MotorState2;
	bool CalibrationFlag;
} Module1DeviceStates, *PModule1DeviceStates;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _Module1UserInputs
{
	LONG Tau1;
	LONG Tau2;
	LONG Tau3;
	bool EnableMotor1;
	bool EnableMotor2;
	bool CalibrationFlag;
} Module1UserInputs, *PModule1UserInputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
#define ADI_Module1DeviceStates 2
#define ADI_Module1UserInputs 3
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
